# 外部应用属性优先级 https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config-application-property-files

# Oracle 19c，
# https://docs.oracle.com/en/database/oracle/oracle-database/21/jjdbc/index.html
# https://docs.oracle.com/en/database/oracle/oracle-database/21/books.html
# MySQL 8.0
# https://dev.mysql.com/doc/index-connectors.html
# https://www.runoob.com/java/java-mysql-connect.html
# PostgreSQL 15
# 驱动程序不需要显示加载，详见 https://jdbc.postgresql.org/documentation/use/
#
#
# jdbc:postgresql://192.168.0.5:5432/dbname?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
# MySQL连接url配置属性，https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-configuration-properties.html

server:
  port: 60001
  servlet:
    context-path: /@project.name@
    encoding:
      charset: UTF-8 # 默认UTF-8
      force: true
      enabled: true
  tomcat: # Tomcat配置调优
    uri-encoding: UTF-8 # 默认UTF-8
    mbeanregistry:
      enabled: false # 默认禁用 JMX Tomcat Bean 暴露
    threads:
      min-spare: 100 # 初始化工作线程数
      max: 500 # 最大工作线程数，有说是CUP核心数的200~250倍之间，但Linux对单个进程有最大线程数限制，
    max-connections: 1600 # 最大链接数
    accept-count: 0 # 当所有可能的请求处理线程都在使用时，传入连接请求的最大队列长度。（最大等待队列长度）
    connection-timeout: 30s # 接受连接后，连接器将等待的时间，以显示请求 URI 行。


################ SpringBoot集成JMX配置：https://www.liaoxuefeng.com/wiki/1252599548343744/1282385687609378 ##############
management:
  server:
    port: 50001
    ssl:
      enabled: false
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true # 启用接口关闭 Spring Boot
  endpoints:
    enabled-by-default: true # 默认情况下是启用还是禁用所有监控点
    web:
      base-path: /actuator # 启用单独的url地址来监控 Spring Boot 应用，默认是 "/actuator"。http://127.0.0.1:50001/actuator
      exposure:
        include: "*" # 打开所有的监控点
    jmx:
      exposure:
        include: "*"

spring:
  application:
    name: @project.name@
  profiles:
    active: @profiles.active@
  jmx:
    enabled: true
  mustache:
    view-names:
  servlet:
    multipart:
      enabled: true
      max-file-size: 2048MB
      max-request-size: 2048MB

# 自定义swagger配置
swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: @project.version@
  application-description: @project.description@
  try-host: http://localhost:${server.port}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html # http://127.0.0.1:60001/mars-service-admin/swagger-ui.html


