# DEV（Development）：开发环境

# DataSource Config
spring:
  datasource:
    name: dataSourceName
    driver-class-name: oracle.jdbc.OracleDriver # Oracle 9i 之后，建议使用 oracle.jdbc.OracleDriver ，而不是 oracle.jdbc.driver.OracleDriver。
    url: jdbc:oracle:thin:@192.168.31.5:1521:orcl
    username: mars
    password: 123456789

