
# https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config-application-property-files

server:
  port: 60001
  servlet:
    context-path: /@project.name@
    encoding:
      charset: UTF-8 # 默认UTF-8
      force: true
      enabled: true
  tomcat:
    uri-encoding: UTF-8 # 默认UTF-8

spring:
  application:
    name: @project.name@ # 需要项目打包以后才能运行
  profiles:
    active: @profiles.active@
  mustache:
    view-names:
  servlet:
    multipart:
      enabled: true
      max-file-size: 2048MB
      max-request-size: 2048MB
  http:
    encoding:
      force: true
  devtools:
    restart:
      enabled: false

# 自定义swagger配置
swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: @project.version@
  application-description: @project.description@
  try-host: http://localhost:${server.port}

logging:
  config: classpath:log4j2.xml

