server:
  port: 8001

# DataSource Config
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.3.206:1521:orcl
    username: base
    password: base
  rabbitmq:
    #addresses: 192.168.3.233:5672,192.168.3.235:5672 # 集群
    host: 192.168.3.233
    port: 5672
    username: admin
    password: 123456
